contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #cci channel"
    url: https://nfcore.slack.com/channels/cci
    about: Discussion about the nf-core/cci pipeline
